/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as StudyIdIndexRouteImport } from './routes/study/$id/index'
import { Route as DeckIdIndexRouteImport } from './routes/deck/$id/index'
import { Route as ApiZeroQueryRouteImport } from './routes/api/zero/query'
import { Route as ApiZeroMutateRouteImport } from './routes/api/zero/mutate'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdIndexRoute = StudyIdIndexRouteImport.update({
  id: '/study/$id/',
  path: '/study/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdIndexRoute = DeckIdIndexRouteImport.update({
  id: '/deck/$id/',
  path: '/deck/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroQueryRoute = ApiZeroQueryRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRoute = ApiZeroMutateRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/deck/$id/': typeof DeckIdIndexRoute
  '/study/$id/': typeof StudyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/deck/$id': typeof DeckIdIndexRoute
  '/study/$id': typeof StudyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/zero/mutate': typeof ApiZeroMutateRoute
  '/api/zero/query': typeof ApiZeroQueryRoute
  '/deck/$id/': typeof DeckIdIndexRoute
  '/study/$id/': typeof StudyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/avatar'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/deck/$id/'
    | '/study/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/avatar'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/deck/$id'
    | '/study/$id'
  id:
    | '__root__'
    | '/'
    | '/api/avatar'
    | '/sign-in/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/deck/$id/'
    | '/study/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiZeroMutateRoute: typeof ApiZeroMutateRoute
  ApiZeroQueryRoute: typeof ApiZeroQueryRoute
  DeckIdIndexRoute: typeof DeckIdIndexRoute
  StudyIdIndexRoute: typeof StudyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id/': {
      id: '/study/$id/'
      path: '/study/$id'
      fullPath: '/study/$id/'
      preLoaderRoute: typeof StudyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id/': {
      id: '/deck/$id/'
      path: '/deck/$id'
      fullPath: '/deck/$id/'
      preLoaderRoute: typeof DeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiZeroMutateRoute: ApiZeroMutateRoute,
  ApiZeroQueryRoute: ApiZeroQueryRoute,
  DeckIdIndexRoute: DeckIdIndexRoute,
  StudyIdIndexRoute: StudyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
